server:
  servlet:
    context-path: /api/mngr/court
  port: 8082

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/fc_court
    username: app_user
    password: kj5BEBMr
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true

application:
  security:
    jwt:
      secret-key: "C2mBOVNCQY2xziZCCSSehBvzou1LIMj2h1AeUDi5sZ2UHVGHvMlO+eW1EIUPj+X92PTTJDBBLhS+6ftNMwjVeg=="

appDescription: "Food Court mngr"
appVersion: "1.0.0"
external:
  api:
    users-mngr:
      url: "localhost:8081/api/v1/mngr/users/"