server:
  servlet:
    context-path: /api/mngr/court
  port: 8082

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/fc_court
    username: app_user
    password: PASSWORD_USER_BD
    driver-class-name: com.mysql.cj.jdbc.Driver
  profiles:
    active: dev

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true

application:
  security:
    jwt:
      secret-key: "SECRET_KEY"

appDescription: "Food Court mngr"
appVersion: "1.0.0"
external:
  api:
    users-mngr:
      url: "localhost:8081/api/v1/mngr/users/"
    notification-mngr:
      url: "localhost:8081/api/v1/mngr/users/"
      account-sid: "ACCOUNT_SID_SECRET"
      auth-token: "AUTH_TOKEN"
      messaging-service-sid: "MESSAGING_SERVICE_SID"